build:
  docs:
    image: nate/mkdocs
    commands:
      - mkdocs build
      - ls site
  deploy:
    image: nate/mkdocs
    commands:
      - ./deploy.sh
    environment:
      - PRIV_KEY="$$PRIV_KEY"
