build:
  docs:
    image: nate/mkdocs:0.15.0
    commands:
      - mkdocs build
      - ls site
  deploy:
    image: nate/mkdocs:0.15.0
    commands:
      - ./deploy.sh
    environment:
      - PRIV_KEY="$$PRIV_KEY"
