site_name: Personal Message Bus
site_url: http://docs.pmb.io/
site_description: Project documentation for PMB.

theme: readthedocs
copyright: Copyright &copy; 2014-2016, <a href="https://twitter.com/ndj">Nate Jones</a>.
repo_url: https://github.com/justone/pmb

pages:
- Home: index.md
- Documentation:
    - Getting Started:
        - Overview: getting_started.md
        - RabbitMQ Docker Image: rabbitmq_docker_image.md
        - Custom RabbitMQ Setup: add_to_existing_rabbitmq.md
    - Configuration: configuration.md
    - Message Descriptions: messages.md
    - Core Functionality: core.md
- Concepts:
    - Introduction: concepts/introduction.md
    - Fact Driven Development: concepts/fact_driven.md
